spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starbook?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: wujinxing718
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        min-idle: 8   # 连接池中的最小空闲连接 默认 0
    timeout: 5000

  thymeleaf:
    cache: false
    mode: HTML5

  mvc:
    static-path-pattern: /static/**
server:
  port: 8090